[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"

[project]
name = "chain-simulator"
version = "0.3.3"
authors = [
    { name = "Max Nollet", email = "mjh.nollet@student.han.nl" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "scipy>=1.10",
]

[project.urls]
Issues = "https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/issues"
Source = "https://github.com/Bovi-analytics/DigitalCowSimulationPlatform"

[project.optional-dependencies]
gpu = [
    "cupy-cuda12x>=12.3.0",
]

[dependency-groups]
dev = [
    "docformatter>=1.7.6",
    "mypy>=1.14.1",
    "pylint>=3.2.7",
    "ruff>=0.14.5",
    "towncrier>=24.8.0",
]
docs = [
    "furo>=2024.8.6",
    "numpydoc>=1.7.0",
    "sphinx>=7.1.2",
    "sphinx-autobuild>=2021.3.14",
    "sphinx-copybutton>=0.5.2",
]
tests = [
    "coverage[toml]>=7.6.1",
    "pytest>=8.3.5",
]


[tool.mypy]
strict = true
plugins = ["numpy.typing.mypy_plugin"]
[[tool.mypy.overrides]]
module = ["cupy.*", "cupyx.*", "scipy.*", "pytest.*", "_pytest.*"]
ignore_missing_imports = true


[tool.ruff]
line-length = 79
show-fixes = true
target-version = "py38"

[tool.ruff.lint]
extend-select = [
    "B",
    "BLE",
    "C4",
    "D",
    "ERA",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PGH",
    "PIE",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "TID",
    "YTT",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test_*.py" = ["S101"]


[tool.towncrier]
directory = "changelog"
filename = "docs/source/changelog.rst"
issue_format = "`#{issue} <https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/issues/{issue}>`_"
name = "Chain Simulator"
package = "chain_simulator"
package_dir = "src"
title_format = "{version} ({project_date})"
wrap = true


[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = ["gpu"]
