# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5
    - name: install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.11"
        enable-cache: true
    - name: Install the project
      run: uv sync --locked --group=docs
    - name: Build the documentation
      run: |
        uv run sphinx-apidoc -f -e -M -o docs/source/generated/ src/chain_simulator/
        uv run sphinx-build -b html docs/source/ docs/build/html
    - name: Configure Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: docs/build/html

  # Based on https://github.com/marketplace/actions/deploy-github-pages-site
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
